/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Marcos Vinicius
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Agendamento extends javax.swing.JFrame {

    /**
     * Creates new form Agendamento
     */
    
    private void carregarDadosTabela() {
        try (Connection conexao = ConexaoBD.obterConexao()) {
        String sql = "SELECT codigo_agendamento, cpf_b1, cpf_b2, cpf_b3, cpf_b4, hora_inicio, hora_termino, codigo_sala, matricula, cpf_professor FROM agendamento";
        try (PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
            ResultSet resultSet = preparedStatement.executeQuery();

            // Limpa a tabela antes de adicionar novos dados
            DefaultTableModel model = (DefaultTableModel) jTableAgendamento.getModel();
            model.setRowCount(0);

            // Adiciona os dados na tabela
            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getString("codigo_agendamento"),
                    resultSet.getString("codigo_sala"),
                    resultSet.getString("cpf_professor"),
                    resultSet.getString("cpf_b1"),
                    resultSet.getString("cpf_b2"),
                    resultSet.getString("cpf_b3"),
                    resultSet.getString("cpf_b4"),
                    resultSet.getString("hora_inicio"),
                    resultSet.getString("hora_termino"),

                };
                model.addRow(row);
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        exibirMensagemErro();
    }
     }
    
    private DefaultTableModel model;
    
    public Agendamento() {
      
        initComponents();
        carregarDadosTabela(); // Adicione esta linha para carregar os dados inicialmente
        
        // iniciar modelo tabela 
        model = new DefaultTableModel();
        jTableAgendamento.setModel(model);
        model.addColumn("Código Agendamento");
        model.addColumn("Código Sala");
        model.addColumn("CPF Professor");
        model.addColumn("CPF Membro 1");
        model.addColumn("CPF Membro 2");
        model.addColumn("CPF Membro 3");
        model.addColumn("CPF Membro 4");
        model.addColumn("Início");
        model.addColumn("Término");
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAgendamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbntCadastrarAgendamento = new javax.swing.JButton();
        jbntEditarAgendamento = new javax.swing.JButton();
        jbntListarAgendamento = new javax.swing.JButton();
        jbntExcluirAgendamento = new javax.swing.JButton();
        jtxtCodigoAgendamento = new javax.swing.JTextField();
        jtxtCodigoSala = new javax.swing.JTextField();
        jtxtMatriculaAluno = new javax.swing.JTextField();
        jtxtCPFProfessor = new javax.swing.JTextField();
        jtxtCPFMembro1 = new javax.swing.JTextField();
        jtxtCPFMembro2 = new javax.swing.JTextField();
        jtxtCPFMembro3 = new javax.swing.JTextField();
        jtxtCPFMembro4 = new javax.swing.JTextField();
        jtxtTermino = new javax.swing.JTextField();
        jtxtInicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgendamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código do Agendamento:");

        jLabel2.setText("Código da Sala:");

        jLabel3.setText("Matrícula do Aluno:");

        jLabel4.setText("CPF do Professor:");

        jLabel5.setText("CPF do Membro 1:");

        jLabel6.setText("CPF do Membro 2:");

        jLabel7.setText("CPF do Membro 3:");

        jLabel8.setText("CPF do Membro 4:");

        jLabel9.setText("Início: ");

        jLabel10.setText("Término:");

        jbntCadastrarAgendamento.setText("Cadastrar");
        jbntCadastrarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntCadastrarAgendamentoActionPerformed(evt);
            }
        });

        jbntEditarAgendamento.setText("Editar");
        jbntEditarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntEditarAgendamentoActionPerformed(evt);
            }
        });

        jbntListarAgendamento.setText("Listar");
        jbntListarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntListarAgendamentoActionPerformed(evt);
            }
        });

        jbntExcluirAgendamento.setText("Excluir");
        jbntExcluirAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntExcluirAgendamentoActionPerformed(evt);
            }
        });

        jtxtCodigoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoSalaActionPerformed(evt);
            }
        });

        jtxtMatriculaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMatriculaAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgendamentoLayout = new javax.swing.GroupLayout(jPanelAgendamento);
        jPanelAgendamento.setLayout(jPanelAgendamentoLayout);
        jPanelAgendamentoLayout.setHorizontalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(41, 41, 41)
                                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(9, 9, 9)
                                .addComponent(jtxtCodigoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))))
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jbntCadastrarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jbntEditarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jbntExcluirAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jbntListarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtCPFMembro1)
                                .addComponent(jtxtCPFMembro2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addComponent(jtxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCPFMembro3))
                            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCPFMembro4)
                                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                                        .addComponent(jtxtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 102, Short.MAX_VALUE)))))))
                .addGap(49, 49, 49))
        );
        jPanelAgendamentoLayout.setVerticalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jtxtCodigoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCPFMembro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCPFMembro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jtxtCPFMembro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCPFMembro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jtxtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtCodigoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbntCadastrarAgendamento)
                    .addComponent(jbntListarAgendamento)
                    .addComponent(jbntExcluirAgendamento)
                    .addComponent(jbntEditarAgendamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Agendamento", "Código Sala", "Matrícula Aluno", "CPF Professor", "CPF Membro 1", "CPF Membro 2", "CPF Membro 3", "CPF Membro 4", "Início", "Término"
            }
        ));
        jScrollPane1.setViewportView(jTableAgendamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbntExcluirAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntExcluirAgendamentoActionPerformed
        // TODO add your handling code here:
        
        String codigo_agendamento = jtxtCodigoAgendamento.getText();
    
    try (Connection conexao = ConexaoBD.obterConexao()) {
        String sql = "DELETE FROM agendamento WHERE codigo_agendamento = ?";
        try (PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
            preparedStatement.setString(1, codigo_agendamento);

            int linhasAfetadas = preparedStatement.executeUpdate();

            if (linhasAfetadas > 0) {
                exibirMensagemSucesso();
            } else {
                exibirMensagemErro();
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        exibirMensagemErro();
    }  
        
        
        
    }//GEN-LAST:event_jbntExcluirAgendamentoActionPerformed

    private void jbntEditarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntEditarAgendamentoActionPerformed
        // TODO add your handling code here:
        
        String codigo_agendamento = jtxtCodigoAgendamento.getText();
        String cpf_b1 = jtxtCPFMembro1.getText();
        String cpf_b2 = jtxtCPFMembro2.getText();
        String cpf_b3 = jtxtCPFMembro3.getText();
        String cpf_b4 = jtxtCPFMembro4.getText();
        String hora_inicio = jtxtInicio.getText();
        String hora_termino = jtxtTermino.getText();
        String codigo_sala = jtxtCodigoSala.getText();
        String matricula = jtxtMatriculaAluno.getText();
        String cpf_professor = jtxtCPFProfessor.getText();

        try (Connection conexao = ConexaoBD.obterConexao()) {
            String sql = "UPDATE agendamento SET  cpf_b1 = ?, cpf_b2 = ?, cpf_b3 = ?, cpf_b4 = ?, hora_inicio = ?, hora_termino = ?, codigo_sala = ?, matricula = ?, cpf_professor = ?  WHERE codigo_agendamento = ?";
            try (PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
                preparedStatement.setString(1, cpf_b1);
                preparedStatement.setString(2, cpf_b2);
                preparedStatement.setString(3, cpf_b3);
                preparedStatement.setString(4, cpf_b4);
                preparedStatement.setString(5, hora_inicio);
                preparedStatement.setString(6, hora_termino);
                preparedStatement.setString(7, codigo_sala);
                preparedStatement.setString(8, matricula);
                preparedStatement.setString(9, cpf_professor);
                preparedStatement.setString(10, codigo_agendamento);


                int linhasAfetadas = preparedStatement.executeUpdate();

                if (linhasAfetadas > 0) {
                    exibirMensagemSucesso();
                } else {
                    exibirMensagemErro();
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            exibirMensagemErro();
        }   
        
        
    }//GEN-LAST:event_jbntEditarAgendamentoActionPerformed

    private void jbntCadastrarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntCadastrarAgendamentoActionPerformed
        // TODO add your handling code here:
        
        
        String codigo_agendamento = jtxtCodigoAgendamento.getText();
        String codigo_sala = jtxtCodigoSala.getText();
        String matricula = jtxtMatriculaAluno.getText();
        String cpf_professor = jtxtCPFProfessor.getText();
        String cpf_b1 = jtxtCPFMembro1.getText();
        String cpf_b2 = jtxtCPFMembro2.getText();
        String cpf_b3 = jtxtCPFMembro3.getText();
        String cpf_b4 = jtxtCPFMembro4.getText();
        String hora_inicio = jtxtInicio.getText();
        String hora_termino = jtxtTermino.getText();
        
        try (Connection conexao = ConexaoBD.obterConexao()) {
            String sql = "INSERT INTO agendamento (codigo_agendamento, cpf_b1, cpf_b2, cpf_b3, cpf_b4, hora_inicio, hora_termino, codigo_sala, matricula, cpf_professor) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
                preparedStatement.setString(1, codigo_agendamento);
                preparedStatement.setString(2, cpf_b1);
                preparedStatement.setString(3, cpf_b2);
                preparedStatement.setString(4, cpf_b3);
                preparedStatement.setString(5, cpf_b4);
                preparedStatement.setString(6, hora_inicio);
                preparedStatement.setString(7, hora_termino);
                preparedStatement.setString(8, codigo_sala);
                preparedStatement.setString(9, matricula);
                preparedStatement.setString(10, cpf_professor);

                int linhasAfetadas = preparedStatement.executeUpdate();

                if (linhasAfetadas > 0) {
                    exibirMensagemSucesso();
                } else {
                    exibirMensagemErro();
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            exibirMensagemErro();
        }  
        
    }//GEN-LAST:event_jbntCadastrarAgendamentoActionPerformed

    private void jtxtCodigoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoSalaActionPerformed

    private void jtxtMatriculaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMatriculaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMatriculaAlunoActionPerformed

    private void jbntListarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntListarAgendamentoActionPerformed
        // TODO add your handling code here:
        carregarDadosTabela(); // Adicione esta linha para carregar os dados inicialmente
    }//GEN-LAST:event_jbntListarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAgendamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgendamento;
    private javax.swing.JButton jbntCadastrarAgendamento;
    private javax.swing.JButton jbntEditarAgendamento;
    private javax.swing.JButton jbntExcluirAgendamento;
    private javax.swing.JButton jbntListarAgendamento;
    private javax.swing.JTextField jtxtCPFMembro1;
    private javax.swing.JTextField jtxtCPFMembro2;
    private javax.swing.JTextField jtxtCPFMembro3;
    private javax.swing.JTextField jtxtCPFMembro4;
    private javax.swing.JTextField jtxtCPFProfessor;
    private javax.swing.JTextField jtxtCodigoAgendamento;
    private javax.swing.JTextField jtxtCodigoSala;
    private javax.swing.JTextField jtxtInicio;
    private javax.swing.JTextField jtxtMatriculaAluno;
    private javax.swing.JTextField jtxtTermino;
    // End of variables declaration//GEN-END:variables

    private void exibirMensagemErro() {
        
        javax.swing.JOptionPane.showMessageDialog(
        this, "Erro ao inserir dados.", "Erro", 
        javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    

    private void exibirMensagemErroExclusao() {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o professor.", "Erro", JOptionPane.ERROR_MESSAGE);

    }

    private void exibirMensagemSucessoExclusao() {
            JOptionPane.showMessageDialog(this, "Professor excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

    }

    private void exibirMensagemErroEdicao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void exibirMensagemSucessoEdicao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void exibirMensagemSucesso() {
        javax.swing.JOptionPane.showMessageDialog(
        this, "Dados inseridos com sucesso!", "Sucesso", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
}
